export const GET_DATA_FROM_SERVER = 'GET_DATA_FROM_SERVER';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';

export const CHANGE_NUMBER_PRODUCT_TO_CART = 'CHANGE_NUMBER_PRODUCT_TO_CART';

export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART';

export const CLEAR_CART = 'CLEAR_CART';

export const SHOW_MODAL = 'SHOW_MODAL';

export const SHOW_LOADER = 'SHOW_LOADER';

export const SHOW_ERROR = 'SHOW_ERROR';


