export const GET_DATA_FROM_SERVER = 'GET_DATA_FROM_SERVER'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'

export const CHANGE_NUMBER_PRODUCT_TO_CART = 'CHANGE_NUMBER_PRODUCT_TO_CART'

export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART'

export const CLEAR_CART = 'CLEAR_CART'



